name: GitHub Actions Demo Bootcamp CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
env:
  DUMMY: Santafe
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      DUMMY: Santafe Campeon 2024
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "El valor de mi_variable es ${{ vars.DUMMY }} ${{ env.DUMMY }} "
