name: GitHub Actions Demo Bootcamp CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: ["main", "workshop1"]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/setup-node@v4
